<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FluidX.TextBuffers.PieceTree" />
    <InternalsVisibleTo Include="FluidX.TextBuffers.PersistentPieceTree" />
    <InternalsVisibleTo Include="FluidX.TextBuffers.LineArrays" />
  </ItemGroup>

</Project>
